#!/usr/bin/env python3
"""Build the Office fixtures in tests/fixtures/office/ from scratch.

The fixtures are small OOXML packages carrying known defects, so the tests can
assert on exact counts. They are committed to the repository because the tests
should not need a build step, and they are generated by this script because a
binary fixture nobody can regenerate is a binary fixture nobody can change.

Each file pairs with a clean equivalent, so a check that fires on the defective
file and stays quiet on the clean one proves it is testing the defect rather
than the format.

Usage:
  python3 tests/fixtures/build_office_fixtures.py
"""

from __future__ import annotations

import pathlib
import zipfile

OUT = pathlib.Path(__file__).resolve().parent / "office"

# A fixed timestamp on every entry, so regenerating a fixture produces the same
# bytes. Without it zipfile stamps the current time and every rebuild shows up
# as a change to a binary file nobody can diff.
FIXED_DATE = (2024, 1, 1, 0, 0, 0)

W = 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"'
WP = ('xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" '
      'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" '
      'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"')
P = ('xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" '
     'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" '
     'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"')
S = 'xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"'
SR = 'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"'

RELS_ROOT = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="{main}"/>
<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
</Relationships>"""


def core_props(title: str = "", language: str = "") -> str:
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/">
<dc:title>{title}</dc:title><dc:creator>Fixture</dc:creator><dc:language>{language}</dc:language>
</cp:coreProperties>"""


def content_types(*overrides: str) -> str:
    return ("""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Default Extension="xml" ContentType="application/xml"/>
<Default Extension="png" ContentType="image/png"/>
<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
"""
            + "\n".join(overrides) + "\n</Types>")


def write(name: str, parts: dict[str, str | bytes]) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / name
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
        for part, data in parts.items():
            info = zipfile.ZipInfo(part, date_time=FIXED_DATE)
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, data)
    print(f"  wrote {path.relative_to(OUT.parent.parent.parent)} "
          f"({path.stat().st_size} bytes)")


# ---------------------------------------------------------------- Word

def paragraph(text: str, style: str | None = None, bold: bool = False,
              size: int | None = None, numbered: bool = False) -> str:
    props = []
    if style:
        props.append(f'<w:pStyle w:val="{style}"/>')
    if numbered:
        props.append('<w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/></w:numPr>')
    ppr = f"<w:pPr>{''.join(props)}</w:pPr>" if props else ""
    rpr = []
    if bold:
        rpr.append("<w:b/>")
    if size:
        rpr.append(f'<w:sz w:val="{size}"/>')
    run_props = f"<w:rPr>{''.join(rpr)}</w:rPr>" if rpr else ""
    return f'{"<w:p>"}{ppr}<w:r>{run_props}<w:t xml:space="preserve">{text}</w:t></w:r></w:p>'


def table(rows: list[list[str]], header_repeat: bool = False,
          look_first_row: bool = False, merge_first: bool = False) -> str:
    look = ('<w:tblLook w:firstRow="1" w:lastRow="0" w:firstColumn="1" '
            'w:lastColumn="0" w:noHBand="0" w:noVBand="1"/>') if look_first_row else ""
    out = [f"<w:tbl><w:tblPr><w:tblW w:w='0' w:type='auto'/>{look}</w:tblPr>"]
    for index, row in enumerate(rows):
        trpr = "<w:trPr><w:tblHeader/></w:trPr>" if index == 0 and header_repeat else ""
        cells = []
        for column, cell in enumerate(row):
            span = ""
            if merge_first and index == 0 and column == 0:
                span = '<w:gridSpan w:val="2"/>'
            cells.append(f"<w:tc><w:tcPr><w:tcW w:w='0' w:type='auto'/>{span}</w:tcPr>"
                         f"{paragraph(cell)}</w:tc>")
        out.append(f"<w:tr>{trpr}{''.join(cells)}</w:tr>")
    out.append("</w:tbl>")
    return "".join(out)


def drawing(name: str, descr: str | None, anchored: bool = False) -> str:
    attr = f' descr="{descr}"' if descr is not None else ""
    frame = "wp:anchor" if anchored else "wp:inline"
    extra = (' behindDoc="0" distT="0" distB="0" distL="0" distR="0" simplePos="0" '
             'relativeHeight="1" locked="0" layoutInCell="1" allowOverlap="1"'
             if anchored else "")
    return (f"<w:p><w:r><w:drawing><{frame}{extra}>"
            f'<wp:extent cx="1000000" cy="1000000"/>'
            f'<wp:docPr id="1" name="{name}"{attr}/>'
            f"</{frame}></w:drawing></w:r></w:p>")


def hyperlink(text: str) -> str:
    return (f'<w:p><w:hyperlink r:id="rId9"><w:r><w:t>{text}</w:t></w:r>'
            f"</w:hyperlink></w:p>")


def styles_xml(default_size: int = 22, heading_styles: bool = True) -> str:
    headings = ""
    if heading_styles:
        for level in range(1, 4):
            headings += (f'<w:style w:type="paragraph" w:styleId="Heading{level}">'
                         f'<w:name w:val="heading {level}"/>'
                         f'<w:pPr><w:outlineLvl w:val="{level - 1}"/></w:pPr></w:style>')
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles {W}>
<w:docDefaults><w:rPrDefault><w:rPr><w:sz w:val="{default_size}"/>
<w:lang w:val="en-US"/></w:rPr></w:rPrDefault></w:docDefaults>
<w:style w:type="paragraph" w:styleId="Normal"><w:name w:val="Normal"/></w:style>
{headings}</w:styles>"""


def docx_parts(body: str, title: str = "", language: bool = True,
               heading_styles: bool = True) -> dict[str, str]:
    styles = styles_xml(heading_styles=heading_styles)
    if not language:
        styles = styles.replace('<w:lang w:val="en-US"/>', "")
    return {
        "[Content_Types].xml": content_types(
            '<Override PartName="/word/document.xml" ContentType="application/vnd.'
            'openxmlformats-officedocument.wordprocessingml.document.main+xml"/>',
            '<Override PartName="/word/styles.xml" ContentType="application/vnd.'
            'openxmlformats-officedocument.wordprocessingml.styles+xml"/>'),
        "_rels/.rels": RELS_ROOT.format(main="word/document.xml"),
        "docProps/core.xml": core_props(title),
        "word/styles.xml": styles,
        "word/_rels/document.xml.rels": """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
<Relationship Id="rId9" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="https://example.gov/annual-report" TargetMode="External"/>
</Relationships>""",
        "word/document.xml": f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                             f"<w:document {W} {WP}><w:body>{body}</w:body></w:document>",
    }


def build_word() -> None:
    defects = "".join([
        paragraph("Quarterly Accessibility Report", bold=True, size=36),
        paragraph("Prepared for the board", bold=True, size=28),
        paragraph("This report covers the period to March."),
        paragraph("Findings", style="Heading3"),
        paragraph("The team reviewed every template."),
        drawing("chart1.png", None),
        drawing("logo.png", "logo.png", anchored=True),
        hyperlink("https://example.gov/annual-report"),
        hyperlink("click here"),
        paragraph("- First manual bullet"),
        paragraph("- Second manual bullet"),
        paragraph("1. First manual number"),
        table([["Region", "Total"], ["North", "12"], ["South", "9"]], merge_first=True),
    ])
    write("report-defects.docx", docx_parts(defects, title="", language=False))

    clean = "".join([
        paragraph("Quarterly Accessibility Report", style="Heading1"),
        paragraph("This report covers the period to March."),
        paragraph("Findings", style="Heading2"),
        paragraph("The team reviewed every template."),
        drawing("chart1.png", "Column chart. Uptake rose from 40 to 62 percent."),
        hyperlink("Read the annual report"),
        paragraph("First bullet", numbered=True),
        paragraph("Second bullet", numbered=True),
        table([["Region", "Total"], ["North", "12"]], header_repeat=True,
              look_first_row=True),
    ])
    write("report-clean.docx", docx_parts(clean, title="Quarterly Accessibility Report"))


# ---------------------------------------------------------------- PowerPoint

def slide(title: str | None, shapes: str = "") -> str:
    title_shape = ""
    if title is not None:
        title_shape = (
            "<p:sp><p:nvSpPr><p:cNvPr id=\"2\" name=\"Title 1\"/><p:cNvSpPr/>"
            "<p:nvPr><p:ph type=\"title\"/></p:nvPr></p:nvSpPr><p:spPr/>"
            f"<p:txBody><a:bodyPr/><a:p><a:r><a:t>{title}</a:t></a:r></a:p></p:txBody></p:sp>")
    return (f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            f"<p:sld {P}><p:cSld><p:spTree>"
            f"<p:nvGrpSpPr><p:cNvPr id=\"1\" name=\"\"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>"
            f"<p:grpSpPr/>{title_shape}{shapes}</p:spTree></p:cSld></p:sld>")


def picture(shape_id: int, name: str, descr: str | None) -> str:
    attr = f' descr="{descr}"' if descr is not None else ""
    return (f'<p:pic><p:nvPicPr><p:cNvPr id="{shape_id}" name="{name}"{attr}/>'
            f"<p:cNvPicPr/><p:nvPr/></p:nvPicPr><p:blipFill/><p:spPr/></p:pic>")


def textbox(shape_id: int, text: str, x: int, y: int) -> str:
    return (f'<p:sp><p:nvSpPr><p:cNvPr id="{shape_id}" name="TextBox {shape_id}"/>'
            f"<p:cNvSpPr txBox=\"1\"/><p:nvPr/></p:nvSpPr>"
            f'<p:spPr><a:xfrm><a:off x="{x}" y="{y}"/>'
            f'<a:ext cx="3000000" cy="800000"/></a:xfrm></p:spPr>'
            f"<p:txBody><a:bodyPr/><a:p><a:r><a:t>{text}</a:t></a:r></a:p></p:txBody></p:sp>")


def pptx_parts(slides: list[str], title: str = "") -> dict[str, str]:
    overrides = ['<Override PartName="/ppt/presentation.xml" ContentType="application/vnd.'
                 'openxmlformats-officedocument.presentationml.presentation.main+xml"/>']
    rels = []
    parts: dict[str, str] = {}
    for index, content in enumerate(slides, start=1):
        parts[f"ppt/slides/slide{index}.xml"] = content
        overrides.append(f'<Override PartName="/ppt/slides/slide{index}.xml" '
                         'ContentType="application/vnd.openxmlformats-officedocument.'
                         'presentationml.slide+xml"/>')
        rels.append(f'<Relationship Id="rId{index}" Type="http://schemas.openxmlformats.'
                    f'org/officeDocument/2006/relationships/slide" '
                    f'Target="slides/slide{index}.xml"/>')
    ids = "".join(f'<p:sldId id="{255 + i}" r:id="rId{i}"/>'
                  for i in range(1, len(slides) + 1))
    parts.update({
        "[Content_Types].xml": content_types(*overrides),
        "_rels/.rels": RELS_ROOT.format(main="ppt/presentation.xml"),
        "docProps/core.xml": core_props(title),
        "ppt/presentation.xml": f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                                f"<p:presentation {P}><p:sldIdLst>{ids}</p:sldIdLst>"
                                f"</p:presentation>",
        "ppt/_rels/presentation.xml.rels":
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/'
            f'relationships">{"".join(rels)}</Relationships>',
    })
    return parts


def build_powerpoint() -> None:
    defects = [
        slide("Programme update", picture(3, "Picture 3", None)),
        slide(None, textbox(4, "Uptake by quarter", 400000, 400000)
              + textbox(5, "Source: internal data", 400000, 3000000)),
        slide("Programme update", picture(6, "Picture 6", "chart.png")),
    ]
    write("deck-defects.pptx", pptx_parts(defects, title=""))

    clean = [
        slide("Programme update",
              picture(3, "Picture 3",
                      "Line chart. Uptake rises each quarter from 40 to 62 percent.")),
        slide("Next steps"),
    ]
    write("deck-clean.pptx", pptx_parts(clean, title="Programme update"))


# ---------------------------------------------------------------- Excel

def sheet_xml(rows: list[list[str]], merges: list[str] | None = None,
              table_part: bool = False) -> str:
    body = []
    for index, row in enumerate(rows, start=1):
        cells = []
        for column, value in enumerate(row):
            ref = f"{chr(ord('A') + column)}{index}"
            cells.append(f'<c r="{ref}" t="inlineStr"><is><t>{value}</t></is></c>')
        body.append(f'<row r="{index}">{"".join(cells)}</row>')
    merge = ""
    if merges:
        cells = "".join(f'<mergeCell ref="{ref}"/>' for ref in merges)
        merge = f'<mergeCells count="{len(merges)}">{cells}</mergeCells>'
    parts = ('<tableParts count="1"><tablePart r:id="rIdT1"/></tableParts>'
             if table_part else "")
    return (f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            f'<worksheet {S} {SR}><sheetData>{"".join(body)}</sheetData>'
            f"{merge}{parts}</worksheet>")


def table_xml(name: str, ref: str, columns: list[str]) -> str:
    entries = "".join(f'<tableColumn id="{i}" name="{c}"/>'
                      for i, c in enumerate(columns, start=1))
    return (f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            f'<table {S} id="1" name="{name}" displayName="{name}" ref="{ref}" '
            f'headerRowCount="1" totalsRowCount="0">'
            f'<autoFilter ref="{ref}"/>'
            f'<tableColumns count="{len(columns)}">{entries}</tableColumns></table>')


def xlsx_parts(sheets: list[tuple[str, str]], title: str = "",
               tables: dict[int, tuple[str, str, list[str]]] | None = None
               ) -> dict[str, str]:
    overrides = ['<Override PartName="/xl/workbook.xml" ContentType="application/vnd.'
                 'openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>']
    rels, entries = [], []
    parts: dict[str, str] = {}
    for index, (name, content) in enumerate(sheets, start=1):
        parts[f"xl/worksheets/sheet{index}.xml"] = content
        overrides.append(f'<Override PartName="/xl/worksheets/sheet{index}.xml" '
                         'ContentType="application/vnd.openxmlformats-officedocument.'
                         'spreadsheetml.worksheet+xml"/>')
        rels.append(f'<Relationship Id="rId{index}" Type="http://schemas.openxmlformats.'
                    f'org/officeDocument/2006/relationships/worksheet" '
                    f'Target="worksheets/sheet{index}.xml"/>')
        if tables and index in tables:
            table_name, ref, columns = tables[index]
            parts[f"xl/tables/table{index}.xml"] = table_xml(table_name, ref, columns)
            parts[f"xl/worksheets/_rels/sheet{index}.xml.rels"] = (
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/'
                'relationships"><Relationship Id="rIdT1" Type="http://schemas.'
                'openxmlformats.org/officeDocument/2006/relationships/table" '
                f'Target="../tables/table{index}.xml"/></Relationships>')
            overrides.append(f'<Override PartName="/xl/tables/table{index}.xml" '
                             'ContentType="application/vnd.openxmlformats-'
                             'officedocument.spreadsheetml.table+xml"/>')
        entries.append(f'<sheet name="{name}" sheetId="{index}" r:id="rId{index}"/>')
    parts.update({
        "[Content_Types].xml": content_types(*overrides),
        "_rels/.rels": RELS_ROOT.format(main="xl/workbook.xml"),
        "docProps/core.xml": core_props(title),
        "xl/workbook.xml": f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                           f"<workbook {S} {SR}><sheets>{''.join(entries)}</sheets>"
                           f"</workbook>",
        "xl/_rels/workbook.xml.rels":
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/'
            f'relationships">{"".join(rels)}</Relationships>',
    })
    return parts


def build_excel() -> None:
    defects = [
        ("Sheet1", sheet_xml([["Regional totals", ""], ["Region", "Total"],
                              ["North", "12"], ["", ""], ["South", "9"]],
                             merges=["A1:B1"])),
        ("Sheet2", sheet_xml([["Notes"], ["Figures in thousands"]])),
    ]
    write("workbook-defects.xlsx", xlsx_parts(defects, title=""))

    clean = [("Regional totals", sheet_xml([["Region", "Total"], ["North", "12"],
                                            ["South", "9"]], table_part=True))]
    write("workbook-clean.xlsx",
          xlsx_parts(clean, title="Regional totals",
                     tables={1: ("RegionalTotals", "A1:B3", ["Region", "Total"])}))


def main() -> int:
    print("Building Office fixtures")
    build_word()
    build_powerpoint()
    build_excel()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
